version: "3.8"
services:
  web:
    container_name: aeropods-web
    image: aeropods/web:latest
    command: yarn run start
    build:
      context: ../packages/web/
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../packages/web:/web
      - /web/node_modules
  api:
    container_name: aeropods-api
    image: aeropods/api:latest
    command: yarn run dev
    build:
      context: ../packages/api/
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../packages/api:/api
      - /api/node_modules
    links:
      - mongodb
  nginx:
    container_name: aeropods-nginx
    image: aeropods/server:latest
    build:
      context: ../packages/nginx/
      dockerfile: docker/Dockerfile.dev
    ports:
      - 80:80
    links:
      - web
      - api
  mongodb:
    container_name: aeropods-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./.cache/mongodb:/data/db
