version: "3.8"
# Definition of services in development enviroment.
services:
  web:
    container_name: aeropods-web
    image: araclx/aeroweb:latest
    command: yarn run start
    build:
      context: ../packages/web/
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../packages/web:/web
      - /web/node_modules

  api:
    container_name: aeropods-api
    image: araclx/aeroapi:latest
    command: yarn run dev
    build:
      context: ../packages/api/
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../packages/api:/api
      - /api/node_modules
    enviroment:
      - MONGODB_URL=mongodb://mongo:27017
      - NODE_ENV=development
    links:
      - mongodb

  # Service responsible for connecting api and web service into one place, into one location - in this case it's localhost:80.
  nginx:
    container_name: aeropods-nginx
    image: araclx/aeroserv:latest
    build:
      context: ../packages/nginx/
      dockerfile: docker/Dockerfile.dev
    ports:
      - 80:80
    links:
      - web
      - api

  mongodb:
    container_name: aeropods-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./.cache/mongodb:/data/db
